[project]
name = "quranic_amilet"
version = "0.1.0"
description = ""
authors = [
    {name = "a.espahbodi",email = "dev.amir.espahbodi@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "typer (>=0.27.1,<0.28.0)",
    "rich (>=15.0.0,<16.0.0)",
    "python-docx (>=1.2.0,<2.0.0)",
    "weasyprint (>=69.0,<70.0)",
    "playwright-stealth (>=2.0.3,<3.0.0)"
]

[tool.poetry]
packages = [{include = "*", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
